// filtersConfig.js
// Listas por defecto para los filtros de ejercicios (partes del cuerpo, equipamiento, objetivos)

export const DEFAULT_AREAS = [
  "Cuello",
  "Hombros",
  "Brazos",
  "Codos",
  "Antebrazos",
  "Muñecas",
  "Manos",
  "Espalda cervical",
  "Espalda dorsal",
  "Espalda lumbar",
  "Pecho / Tórax",
  "Abdomen / Core",
  "Cadera",
  "Glúteos",
  "Muslos (cuádriceps)",
  "Isquiotibiales",
  "Aductores",
  "Rodillas",
  "Pantorrillas / Gemelos",
  "Tobillos",
  "Pies",
];

export const DEFAULT_EQUIPMENT = [
  "Sin material",
  "Esterilla",
  "Banda elástica / Theraband",
  "Banda de miniband",
  "Mancuernas",
  "Kettlebell",
  "Fitball",
  "Bosu",
  "Foam roller / Rodillo",
  "Steps / Caja pliométrica",
  "Polea / Máquina de cables",
  "TRX / Entrenamiento en suspensión",
  "Barra",
  "Discos de deslizamiento",
  "Banda de cadera (hip band)",
  "Rueda abdominal",
  "Banco",
  "Bicicleta estática",
  "Cinta de correr",
  "Elíptica",
];

export const DEFAULT_GOALS = [
  "Mejorar fuerza",
  "Mejorar movilidad",
  "Mejorar estabilidad",
  "Rehabilitación",
  "Prevenir lesiones",
  "Recuperación post-lesión",
  "Activación muscular",
  "Aumento de flexibilidad",
  "Resistencia general",
  "Hipertrofia (ganar músculo)",
  "Corrección postural",
  "Adelgazamiento / pérdida de peso",
  "Mejora del equilibrio",
  "Mejora de la coordinación",
  "Aumento de rango de movimiento",
  "Reducción del dolor",
  "Reeducación del movimiento",
  "Trabajo de core",
];
